### ISSUE TITLE
gmail.com is broken

### ISSUE THREAD

**Issue by jdoe6** [autonome/forcegooglelocale#2]
https://gmail.com currently redirects to https://www.google.com/gmail/. The extension then appends `?hl=en` to the link, resulting in https://www.google.com/gmail/?hl=en. This causes the server to respond with 404 error. Without the extension, the link works fine.

**Comment by autonome** [comment]
Thanks for filing, and I'm sorry I did not notice.

I cannot reproduce this - I always end up gmail.google.com.

What browser version and which locale?

**Comment by autonome** [comment]
closed, no reply
